# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

camunda:
  client:
    mode: saas
    auth:
      client-id: _xVJDiJelXOsffnEwWYwKrlUQLS0ffOA
      client-secret: ib2djoTf3XKu.5scgqwij4nW61fZZUjyku_F~mdhUhW2EB~_N6s-kYXu.i2zZIcM
    cluster-id: 223154c3-0313-4da4-a9a6-801e22e38ffc
    region: fra-1


# this is to allow react application launched separately to access the WS
websocket:
  allowedOrigin: "*"

springdoc.swagger-ui.path: /swagger-ui.html

spring:
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 30MB

  security.oauth2:
    enabled: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
